# Generated by Django 4.2.16 on 2026-04-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('quote', models.TextField()),
                ('avatar', models.URLField(max_length=500)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(max_length=500)),
                ('hover_image', models.URLField(max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('option_groups', models.JSONField(blank=True, default=list)),
                ('trust_badges', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.collection')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='store.tag')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
