# Generated by Django 4.2.16 on 2026-04-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(default='', max_length=255)),
                ('title_ar', models.CharField(default='', max_length=255)),
                ('excerpt_en', models.TextField(default='')),
                ('excerpt_ar', models.TextField(default='')),
                ('image', models.URLField(default='', max_length=500)),
                ('published_at', models.DateField()),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroPromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title_en', models.CharField(default='', max_length=255)),
                ('title_ar', models.CharField(default='', max_length=255)),
                ('subtitle_en', models.TextField(blank=True, default='')),
                ('subtitle_ar', models.TextField(blank=True, default='')),
                ('cta_en', models.CharField(blank=True, default='', max_length=120)),
                ('cta_ar', models.CharField(blank=True, default='', max_length=120)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('size', models.CharField(choices=[('large', 'Large'), ('small', 'Small')], default='small', max_length=12)),
                ('accent', models.CharField(default='soft', max_length=40)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(default='', max_length=500)),
                ('href', models.URLField(default='', max_length=500)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_prefix_en', models.CharField(blank=True, max_length=20)),
                ('price_prefix_ar', models.CharField(blank=True, max_length=20)),
                ('unit_price_text_en', models.CharField(blank=True, max_length=120)),
                ('unit_price_text_ar', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('region__sort_order', 'product__sort_order'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('code', models.SlugField(max_length=12, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('currency_code', models.CharField(max_length=3)),
                ('locale_code', models.CharField(default='en', max_length=12)),
                ('shipping_threshold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address_en', models.TextField()),
                ('address_ar', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Enfant Organics', max_length=120)),
                ('announcement_en', models.CharField(max_length=255)),
                ('announcement_ar', models.CharField(max_length=255)),
                ('footer_about_en', models.TextField()),
                ('footer_about_ar', models.TextField()),
                ('newsletter_title_en', models.CharField(max_length=255)),
                ('newsletter_title_ar', models.CharField(max_length=255)),
                ('newsletter_subtitle_en', models.TextField()),
                ('newsletter_subtitle_ar', models.TextField()),
                ('instagram_title_en', models.CharField(max_length=255)),
                ('instagram_title_ar', models.CharField(max_length=255)),
                ('instagram_cta_en', models.CharField(max_length=120)),
                ('instagram_cta_ar', models.CharField(max_length=120)),
                ('blog_title_en', models.CharField(max_length=255)),
                ('blog_title_ar', models.CharField(max_length=255)),
                ('free_gift_title_en', models.CharField(max_length=255)),
                ('free_gift_title_ar', models.CharField(max_length=255)),
                ('free_gift_subtitle_en', models.TextField()),
                ('free_gift_subtitle_ar', models.TextField()),
                ('why_choose_links', models.JSONField(blank=True, default=list)),
                ('policy_links', models.JSONField(blank=True, default=list)),
                ('static_links', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option_groups',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trust_badges',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='location',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_ar',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_en',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='details_ar',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='details_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='option_groups_ar',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='option_groups_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_ar',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_baby_sets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_new_arrivals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_top_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_ar',
            field=models.CharField(default='إنفانت أورجانيكس', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_en',
            field=models.CharField(default='Enfant Organics', max_length=120),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location_ar',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location_en',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='store.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='store.region'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'region')},
        ),
    ]
