# Generated by Django 4.2.16 on 2026-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_blogpost_image_file_category_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('whatsapp', 'WhatsApp confirmation'), ('bank_transfer', 'Bank transfer'), ('stripe', 'Stripe'), ('tap', 'Tap Payments'), ('paytabs', 'PayTabs'), ('hyperpay', 'HyperPay'), ('checkout_com', 'Checkout.com')], default='cod', max_length=32),
        ),
    ]
