# Generated by Django 4.2.16 on 2026-05-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_newslettersubscription_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('whatsapp', 'WhatsApp confirmation'), ('bank_transfer', 'Bank transfer'), ('online', 'Online payment placeholder'), ('paymob', 'Paymob'), ('stripe', 'Stripe'), ('tap', 'Tap Payments'), ('paytabs', 'PayTabs'), ('hyperpay', 'HyperPay'), ('checkout_com', 'Checkout.com')], default='cod', max_length=32),
        ),
    ]
