# Generated by Django 4.2.16 on 2026-05-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_tax_applies_to_shipping_order_tax_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_access_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='region',
            name='seller_address_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='region',
            name='seller_address_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='region',
            name='seller_cr_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='region',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='region',
            name='seller_legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='seller_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='seller_vat_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
