# Generated by Django 4.2.16 on 2026-05-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_invoice_access_token_order_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='building',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='floor',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='location_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='region',
            name='require_map_pin',
            field=models.BooleanField(default=False),
        ),
    ]
