# Generated by Django 4.2.16 on 2026-05-12 21:22

from django.db import migrations, models
import store.domain_models.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customeraddress_apartment_customeraddress_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='default_payment_provider',
            field=models.CharField(choices=[('paymob', 'Paymob'), ('paytabs', 'PayTabs'), ('hyperpay', 'HyperPay'), ('telr', 'Telr'), ('thawani', 'Thawani'), ('omannet', 'OmanNet')], default='paymob', max_length=32),
        ),
        migrations.AddField(
            model_name='region',
            name='payment_enabled_providers',
            field=models.JSONField(blank=True, default=store.domain_models.catalog.default_enabled_payment_providers),
        ),
        migrations.AddField(
            model_name='region',
            name='payment_mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=12),
        ),
        migrations.AddField(
            model_name='region',
            name='payment_supported_methods',
            field=models.JSONField(blank=True, default=store.domain_models.catalog.default_supported_payment_methods),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('whatsapp', 'WhatsApp confirmation'), ('bank_transfer', 'Bank transfer'), ('online', 'Online payment placeholder'), ('paymob', 'Paymob'), ('stripe', 'Stripe'), ('tap', 'Tap Payments'), ('paytabs', 'PayTabs'), ('hyperpay', 'HyperPay'), ('telr', 'Telr'), ('thawani', 'Thawani'), ('omannet', 'OmanNet'), ('checkout_com', 'Checkout.com')], default='cod', max_length=32),
        ),
    ]
