# Generated by Django 4.2.16 on 2026-05-12 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_region_default_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_carrier_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_eta_max_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_eta_min_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('flat', 'Flat region shipping'), ('rule_based', 'Rules-based shipping'), ('carrier', 'Carrier-calculated shipping')], default='flat', max_length=32),
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eta_min_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eta_max_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='store.region')),
            ],
            options={
                'ordering': ('region__sort_order', 'region__id', '-active', 'city', 'area', '-min_order_value', 'id'),
            },
        ),
    ]
