# Generated by Django 4.2.16 on 2026-05-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_order_shipping_carrier_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="carrier_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="region",
            name="fallback_carrier",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("aramex", "Aramex"),
                    ("smsa", "SMSA"),
                    ("fetchr", "Fetchr/Equivalent"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="primary_carrier",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("aramex", "Aramex"),
                    ("smsa", "SMSA"),
                    ("fetchr", "Fetchr/Equivalent"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
    ]
