# Generated by Django 4.2.16 on 2026-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_region_carrier_enabled_region_fallback_carrier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="shipment_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("created", "Created"),
                    ("in_transit", "In transit"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("manual", "Manual"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
    ]
