# Generated by Django 4.2.16 on 2026-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_order_carrier_order_shipment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("new_order", "New order"),
                    ("paid_order", "Paid order"),
                    ("payment_review", "Payment review needed"),
                    ("low_stock", "Low stock alert"),
                    ("shipment_update", "Shipment update"),
                ],
                max_length=40,
            ),
        ),
    ]
