# Generated by Django 4.2.16 on 2026-05-13 04:07

from django.db import migrations, models
import django.db.models.deletion


def _normalize_code(value):
    raw = str(value or "").strip().lower().replace(" ", "-")
    keep = []
    for char in raw:
        if char.isalnum() or char == "-":
            keep.append(char)
    normalized = "".join(keep).strip("-")
    return normalized or "default"


def seed_default_warehouses_and_stock(apps, schema_editor):
    Region = apps.get_model("store", "Region")
    Product = apps.get_model("store", "Product")
    Warehouse = apps.get_model("store", "Warehouse")
    ProductStock = apps.get_model("store", "ProductStock")

    for region in Region.objects.all():
        base_code = _normalize_code(f"{region.code}-default")
        code = base_code
        suffix = 1
        while Warehouse.objects.filter(code=code).exclude(region=region).exists():
            suffix += 1
            code = f"{base_code}-{suffix}"

        warehouse, _ = Warehouse.objects.get_or_create(
            region=region,
            code=code,
            defaults={
                "name_en": f"{region.name_en} Main Warehouse",
                "name_ar": f"{region.name_ar} المخزن الرئيسي",
                "city": "",
                "address": region.address_en or "",
                "active": True,
            },
        )
        region.fulfillment_warehouses.add(warehouse)

        for product in Product.objects.filter(track_inventory=True):
            ProductStock.objects.get_or_create(
                product=product,
                warehouse=warehouse,
                defaults={
                    "quantity": int(product.stock_quantity or 0),
                    "reserved_quantity": 0,
                    "low_stock_threshold": 10,
                },
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_notificationlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_released',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='store.region')),
            ],
            options={
                'ordering': ('region__sort_order', 'region__id', 'code'),
            },
        ),
        migrations.AddField(
            model_name='region',
            name='fulfillment_warehouses',
            field=models.ManyToManyField(blank=True, related_name='fulfillment_regions', to='store.warehouse'),
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='store.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='store.warehouse')),
            ],
            options={
                'ordering': ('warehouse__region__sort_order', 'warehouse__code', 'product__sort_order'),
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.RunPython(seed_default_warehouses_and_stock, noop_reverse),
    ]
