# Generated by Django 4.2.16 on 2026-05-13 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def backfill_order_status_workflow(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    OrderStatusHistory = apps.get_model("store", "OrderStatusHistory")

    legacy_status_map = {
        "preparing": "processing",
        "ready": "processing",
        "out_for_delivery": "shipped",
    }
    for legacy_status, mapped_status in legacy_status_map.items():
        Order.objects.filter(status=legacy_status).update(status=mapped_status)

    allowed_statuses = {
        "pending",
        "confirmed",
        "paid",
        "processing",
        "shipped",
        "delivered",
        "cancelled",
        "returned",
        "refunded",
        "failed",
    }
    Order.objects.exclude(status__in=allowed_statuses).update(status="pending")

    Order.objects.filter(status="delivered", delivered_at__isnull=True).update(delivered_at=F("updated_at"))

    existing_order_ids = set(OrderStatusHistory.objects.values_list("order_id", flat=True))
    backfill_rows = [
        OrderStatusHistory(
            order_id=order.id,
            old_status=None,
            new_status=order.status,
            note="Backfilled during order workflow migration.",
        )
        for order in Order.objects.all().iterator()
        if order.id not in existing_order_ids
    ]
    if backfill_rows:
        OrderStatusHistory.objects.bulk_create(backfill_rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_order_inventory_released_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=32, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_history_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order')),
            ],
            options={
                'ordering': ('timestamp', 'id'),
            },
        ),
        migrations.RunPython(backfill_order_status_workflow, migrations.RunPython.noop),
    ]
