# Generated by Django 4.2.16 on 2026-05-13 10:37

from django.db import migrations, models
import django.db.models.deletion


def backfill_notification_log_fields(apps, schema_editor):
    NotificationLog = apps.get_model("store", "NotificationLog")

    event_map = {
        "new_order": "order_created",
        "paid_order": "payment_paid",
    }

    for log in NotificationLog.objects.all().iterator():
        payload = log.payload or {}

        updates = []
        mapped_event = event_map.get(log.event)
        if mapped_event and mapped_event != log.event:
            log.event = mapped_event
            updates.append("event")

        channel = str(payload.get("channel", "") or "").strip().lower()
        if channel in {"email", "sms", "whatsapp", "push", "system"} and log.channel != channel:
            log.channel = channel
            updates.append("channel")

        if not log.status:
            log.status = "sent" if log.success else "failed"
            updates.append("status")
        elif log.status == "pending":
            log.status = "sent" if log.success else "failed"
            updates.append("status")

        if not log.provider:
            if log.channel == "push":
                log.provider = "expo"
            elif log.channel == "email":
                log.provider = "smtp"
            elif log.channel in {"sms", "whatsapp"}:
                log.provider = "internal"
            else:
                log.provider = "internal"
            updates.append("provider")

        if not log.recipient and log.channel in {"email", "sms", "whatsapp"}:
            recipient = str(payload.get("recipient", "") or "").strip()
            if recipient:
                log.recipient = recipient
                updates.append("recipient")

        if updates:
            updates.append("success")
            log.success = log.status != "failed"
            log.save(update_fields=sorted(set(updates)))


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_refund_amount_order_refund_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('system', 'System'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='store.order'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('order_created', 'Order created'), ('payment_paid', 'Payment paid'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('order_cancelled', 'Order cancelled'), ('return_requested', 'Return requested'), ('refund_processed', 'Refund processed'), ('review_request', 'Review request'), ('payment_review', 'Payment review needed'), ('low_stock', 'Low stock alert'), ('shipment_update', 'Shipment update')], max_length=40),
        ),
        migrations.RunPython(backfill_notification_log_fields, migrations.RunPython.noop),
    ]
