# Generated by Django 5.2.5 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_notificationlog_channel_notificationlog_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sms_opt_in",
            field=models.BooleanField(default=False),
        ),
    ]
