# Generated by Django 5.2.5 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_order_sms_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="whatsapp_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WhatsAppLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(choices=[("order_created", "Order confirmed"), ("order_shipped", "Order shipped"), ("order_delivered", "Order delivered"), ("refund_processed", "Refund processed"), ("delivery_receipt", "Delivery receipt")], max_length=40)),
                ("recipient", models.CharField(blank=True, default="", max_length=255)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("template_name", models.CharField(blank=True, default="", max_length=120)),
                ("provider", models.CharField(default="whatsapp_cloud", max_length=40)),
                ("provider_message_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("delivered", "Delivered"), ("read", "Read"), ("failed", "Failed"), ("skipped", "Skipped")], default="pending", max_length=20)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("webhook_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="whatsapp_logs", to="store.order")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
