# Generated by Django 4.2.16 on 2026-05-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0023_order_whatsapp_opt_in_whatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_price_changed', 'Product price changed'), ('coupon_changed', 'Coupon changed'), ('order_status_changed', 'Order status changed'), ('refund_action', 'Refund action'), ('staff_role_changed', 'Staff role changed'), ('site_settings_changed', 'Site settings changed')], db_index=True, max_length=80)),
                ('resource_type', models.CharField(db_index=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp', '-id'),
            },
        ),
    ]
