# Generated by Django 4.2.16 on 2026-05-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_sitesettings_branding_social_seo_legal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='VAT', max_length=120)),
                ('name_ar', models.CharField(blank=True, default='ضريبة القيمة المضافة', max_length=120)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Decimal rate, e.g. 0.05 for 5%.', max_digits=5)),
                ('is_inclusive', models.BooleanField(default=False, help_text='True if prices already include this tax.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('region', models.ForeignKey(blank=True, help_text='Leave blank to apply globally across all regions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='store.region')),
            ],
            options={
                'ordering': ('region__code', 'name_en'),
            },
        ),
    ]
