# Generated by Django 4.2.16 on 2026-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_add_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='algolia_app_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='algolia_search_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cloudinary_api_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cloudinary_cloud_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_business_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_catalog_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shippo_api_token',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_api_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zapier_order_webhook',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zendesk_api_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='zendesk_subdomain',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
