# Generated by Django 4.2.16 on 2026-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_add_remaining_integration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
