# Generated by Django 4.2.16 on 2026-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_add_giftcard_abandonedcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymobRegionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(choices=[('OM', 'Oman (OMR)'), ('SA', 'Saudi Arabia (SAR)'), ('AE', 'United Arab Emirates (AED)')], max_length=2, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='When off, Paymob is treated as disabled for this region even if credentials exist.')),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('integration_id', models.CharField(blank=True, default='', max_length=20)),
                ('iframe_id', models.CharField(blank=True, default='', max_length=20)),
                ('hmac_secret', models.CharField(blank=True, default='', max_length=200)),
                ('base_url', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Paymob region config',
                'verbose_name_plural': 'Paymob region configs',
                'ordering': ('region_code',),
            },
        ),
    ]
