# Generated by Django 4.2.16 on 2026-05-29 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0038_add_analytics_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInStockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified')], default='pending', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GiftCardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('released', 'Released')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='store_analy_event_t_6ec285_idx',
            old_name='store_analy_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='store_analy_session_0ccde5_idx',
            old_name='store_analy_session_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='giftcardredemption',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='store.giftcard'),
        ),
        migrations.AddField(
            model_name='giftcardredemption',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_redemption', to='store.order'),
        ),
        migrations.AddField(
            model_name='backinstockrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_requests', to='store.product'),
        ),
        migrations.AddField(
            model_name='backinstockrequest',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_in_stock_requests', to='store.region'),
        ),
        migrations.AddField(
            model_name='backinstockrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_in_stock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='giftcardredemption',
            unique_together={('gift_card', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='backinstockrequest',
            unique_together={('product', 'region', 'email')},
        ),
    ]
