# Generated by Django 4.2.16 on 2026-05-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_backinstockrequest_giftcardredemption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('title_en', models.CharField(default='', max_length=255)),
                ('title_ar', models.CharField(default='', max_length=255)),
                ('body_en', models.TextField(default='')),
                ('body_ar', models.TextField(default='')),
                ('seo_title_en', models.CharField(blank=True, default='', max_length=255)),
                ('seo_title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description_en', models.TextField(blank=True, default='')),
                ('seo_description_ar', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages', to='store.region')),
            ],
            options={
                'ordering': ('slug', 'region__sort_order', 'region__id', '-updated_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='cmspage',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', True)), fields=('slug',), name='uniq_cms_page_slug_global'),
        ),
        migrations.AddConstraint(
            model_name='cmspage',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', False)), fields=('slug', 'region'), name='uniq_cms_page_slug_region'),
        ),
    ]
