# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0040_cmspage_cmspage_uniq_cms_page_slug_global_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="conversion_attribution",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="conversion_session_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
