# Generated by Django 4.2.16 on 2026-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_order_conversion_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('skipped_no_email', 'Skipped (no customer email)'), ('skipped_draft_order', 'Skipped (draft order)')], default='pending', max_length=20),
        ),
    ]
