# Generated by Django 4.2.16 on 2026-06-11 16:31

from decimal import Decimal

from django.db import migrations, models

# Seed sensible defaults for existing regions (pegged OMR rates).
# Base (OMR) = 1; safe to re-run, admins can edit afterwards.
DEFAULT_FX_RATES = {"om": Decimal("1"), "ae": Decimal("9.55"), "sa": Decimal("9.75")}


def seed_fx_rates(apps, schema_editor):
    Region = apps.get_model("store", "Region")
    for code, rate in DEFAULT_FX_RATES.items():
        Region.objects.filter(code=code).update(fx_rate=rate)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_widen_product_slug_to_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text="Currency conversion rate FROM the base/default region currency. The base region itself stays 1. Used by 'Apply conversion rates' to recompute this region's product prices from the base price.", max_digits=12),
        ),
        migrations.RunPython(seed_fx_rates, noop),
    ]
