# Generated by Django 4.2.16 on 2026-06-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_cartmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropromocard',
            name='image_file_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='hero-cards/'),
        ),
        migrations.AddField(
            model_name='heropromocard',
            name='image_mobile',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
