# Generated by Django 4.2.16 on 2026-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_heropromocard_image_file_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropromocard',
            name='eyebrow_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='heropromocard',
            name='eyebrow_en',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
