# Generated by Django 4.2.16 on 2026-06-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_heropromocard_eyebrow_ar_heropromocard_eyebrow_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropromocard',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='heropromocard',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
