# Generated by Django 4.2.16 on 2026-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_heropromocard_title_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
