# Generated by Django 4.2.16 on 2026-06-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_remove_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_ar',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_en',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='Enfant', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_ar',
            field=models.CharField(blank=True, default='إنفانت أورجانيكس', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_en',
            field=models.CharField(blank=True, default='Enfant Organics', max_length=120),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
