# Generated by Django 4.2.16 on 2026-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_alter_warehouse_options_blogpost_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymobregionconfig',
            name='apple_pay_integration_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymobregionconfig',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='paymobregionconfig',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
