# Generated by Django 4.2.16 on 2026-07-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_paymobregionconfig_apple_pay_integration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('order_created', 'Order created'), ('payment_paid', 'Payment paid'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('order_cancelled', 'Order cancelled'), ('return_requested', 'Return requested'), ('refund_processed', 'Refund processed'), ('review_request', 'Review request'), ('payment_review', 'Payment review needed'), ('low_stock', 'Low stock alert'), ('shipment_update', 'Shipment update'), ('admin_new_order', 'New order (staff alert)')], max_length=40),
        ),
    ]
