# Generated by Django 4.2.16 on 2026-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_alter_notificationlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent (accepted by relay)'), ('delivered', 'Delivered'), ('deferred', 'Deferred (retrying)'), ('bounced', 'Bounced'), ('blocked', 'Blocked'), ('spam', 'Marked as spam'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('skipped_no_email', 'Skipped (no customer email)'), ('skipped_draft_order', 'Skipped (draft order)')], default='pending', max_length=20),
        ),
    ]
