# Generated by Django 4.2.16 on 2026-08-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_alter_notificationlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meta_client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meta_client_user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='meta_event_source_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='meta_fbc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='meta_fbp',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_capi_access_token',
            field=models.TextField(blank=True, default='', help_text='System User token from Events Manager. Never exposed to the storefront.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_capi_dataset_id',
            field=models.CharField(blank=True, default='', help_text='Leave blank to reuse the Facebook Pixel ID.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_capi_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_capi_test_event_code',
            field=models.CharField(blank=True, default='', help_text='Set while verifying in Events Manager → Test Events. CLEAR IT to go live.', max_length=50),
        ),
        migrations.CreateModel(
            name='MetaCapiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=40)),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('event_source_url', models.CharField(blank=True, default='', max_length=500)),
                ('test_event_code', models.CharField(blank=True, default='', max_length=50)),
                ('match_field_count', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_capi_events', to='store.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_name', 'status', 'created_at'], name='store_metac_event_n_cd1e33_idx')],
            },
        ),
    ]
