# Generated by Django 4.2.16 on 2026-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_order_meta_client_ip_order_meta_client_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_is_estimated',
            field=models.BooleanField(default=False, help_text="True when the cost was filled in after the sale from the product's current cost price, rather than captured at the moment the order was placed."),
        ),
    ]
