# Generated by Django 4.2.16 on 2026-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_orderitem_cost_is_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_ar',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
