# Generated by Django 4.2.16 on 2026-08-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_product_unit_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='delivery_eta_max_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='delivery_eta_min_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
