# Generated by Django 4.2.16 on 2026-08-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_region_delivery_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='urgency_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='urgency_text_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='urgency_text_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
