# Generated by Django 4.2.16 on 2026-08-20 03:46

from django.db import migrations, models


def seed_slides_from_large_cards(apps, schema_editor):
    """Carry the existing homepage banner over to the new carousel.

    The banner used to be the first ``size="large"`` HeroPromoCard. Copying it
    into a slide keeps the live homepage looking identical after deploy; hiding
    the source card is what stops the same artwork rendering twice (once in the
    carousel, once in the promo showcase below it).
    """
    HeroPromoCard = apps.get_model('store', 'HeroPromoCard')
    HeroBannerSlide = apps.get_model('store', 'HeroBannerSlide')

    cards = HeroPromoCard.objects.filter(size='large', is_visible=True).order_by('sort_order', 'id')
    for index, card in enumerate(cards):
        HeroBannerSlide.objects.create(
            image=card.image or '',
            image_file=card.image_file.name if card.image_file else None,
            image_mobile=card.image_mobile or '',
            image_file_mobile=card.image_file_mobile.name if card.image_file_mobile else None,
            alt_text_en=card.title_en or '',
            alt_text_ar=card.title_ar or '',
            href=card.href or '',
            sort_order=index,
            is_visible=True,
        )
        card.is_visible = False
        card.save(update_fields=['is_visible'])


def unseed_slides(apps, schema_editor):
    # Nothing to undo beyond dropping the table, which the reverse of
    # CreateModel already handles. The source cards stay hidden — flipping them
    # back on blindly would resurrect cards an admin may have hidden since.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_sitesettings_urgency_strip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='hero-banner/')),
                ('image_mobile', models.URLField(blank=True, default='', max_length=500)),
                ('image_file_mobile', models.ImageField(blank=True, null=True, upload_to='hero-banner/')),
                ('alt_text_en', models.CharField(blank=True, default='', max_length=255)),
                ('alt_text_ar', models.CharField(blank=True, default='', max_length=255)),
                ('href', models.CharField(blank=True, default='', max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_slides_from_large_cards, unseed_slides),
    ]
