# Generated by Django 4.2.16 on 2026-08-23 10:50

"""Give phone artwork its own upload folder.

Both banner images were landing in ``hero-banner/``, so the website and mobile
versions of the same slide were indistinguishable on disk. Only affects new
uploads — existing files keep whatever path is already recorded against them.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_hero_banner_slide_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobannerslide',
            name='image_file_mobile',
            field=models.ImageField(blank=True, height_field='image_mobile_height', null=True, upload_to='hero-banner/mobile/', width_field='image_mobile_width'),
        ),
    ]
