# Generated by Django 4.2.16 on 2026-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_hero_banner_mobile_upload_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, default='', help_text='Barcode / EAN-13, e.g. 8852525753631.', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Internal stock code, e.g. ATNHP3.', max_length=120),
        ),
    ]
