# Generated by Django 4.2.16 on 2026-09-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_product_ean_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, default='', help_text='Overrides the global pixel for this market. Blank = use the global one.', max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_capi_access_token',
            field=models.TextField(blank=True, default='', help_text="System User token for this market's dataset. Never exposed to the storefront."),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_capi_dataset_id',
            field=models.CharField(blank=True, default='', help_text="Leave blank to reuse this market's pixel ID.", max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_capi_test_event_code',
            field=models.CharField(blank=True, default='', help_text='Set while verifying in Events Manager → Test Events. CLEAR IT to go live.', max_length=50),
        ),
    ]
