# Generated by Django 4.2.16 on 2026-09-30 13:02

from django.db import migrations, models
import store.domain_models.catalog


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_product_fbt_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_sections',
            field=models.JSONField(blank=True, default=dict, help_text='Product page sections: {features, how_it_works, comparison}. Edited from the admin panel; leave empty to hide them.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_proof_items',
            field=models.JSONField(blank=True, default=store.domain_models.catalog.default_social_proof_items, help_text='Scrolling proof ticker on product pages. Each item: {text_en, text_ar}. Leave empty to hide.'),
        ),
    ]
