# Generated by Django 4.2.16 on 2026-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_product_page_sections_social_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_showcase',
            field=models.JSONField(blank=True, default=dict, help_text='Reviews showcase (moving images, photo strip, headings). Edited from the admin panel.'),
        ),
    ]
