from datetime import date

ASSET_BASE = "/enfant"
ENFANT_ASSETS = {
    "logo": f"{ASSET_BASE}/enfant-logo.png",
    "double_moisture": f"{ASSET_BASE}/double-moisture-lotion.png",
    "extra_mild": f"{ASSET_BASE}/extra-mild-moisture-lotion.jpg",
    "relax": f"{ASSET_BASE}/relax-moisturizing-lotion.png",
    "daily_sun": f"{ASSET_BASE}/daily-sun-protection-lotion.png",
    "face_body_sunscreen": f"{ASSET_BASE}/face-body-sunscreen-lotion.png",
    "insect_repellent": f"{ASSET_BASE}/insect-repellent-lotion.png",
    "wipes": f"{ASSET_BASE}/extra-mild-baby-wipes.jpg",
    "moisture_shampoo": f"{ASSET_BASE}/moisture-shampoo.png",
    "complete_care": f"{ASSET_BASE}/complete-care-cream.jpg",
}


SITE_SETTINGS = {
    "brand_name": "Enfant Organics",
    "announcement_en": "Enjoy 15% OFF on your order — Use code WELCOME15 at checkout to add discount ✨",
    "announcement_ar": "استمتع بخصم 15% على طلبك — استخدم الكود WELCOME15 عند الدفع للحصول على الخصم ✨",
    "footer_about_en": "We are proud to bring you baby care products that are dermatologically tested by experts in Germany, ensuring the highest standards of safety and quality.",
    "footer_about_ar": "نفخر بتقديم منتجات عناية بالأطفال تم اختبارها من قبل خبراء الجلدية في ألمانيا لضمان أعلى معايير الأمان والجودة.",
    "newsletter_title_en": "Get free gift on Your First Order",
    "newsletter_title_ar": "احصل على هدية مجانية مع أول طلب",
    "newsletter_subtitle_en": "Subscribe to our newsletter and receive an exclusive discount code in your inbox!",
    "newsletter_subtitle_ar": "اشترك في نشرتنا البريدية واحصل على كود خصم حصري في بريدك الإلكتروني!",
    "instagram_title_en": "Join Our Instagram Family",
    "instagram_title_ar": "انضم إلى عائلة إنستغرام الخاصة بنا",
    "instagram_cta_en": "Explore Now",
    "instagram_cta_ar": "استكشف الآن",
    "blog_title_en": "Blog Posts",
    "blog_title_ar": "مقالات المدونة",
    "free_gift_title_en": "Free Shipping & Original Products",
    "free_gift_title_ar": "شحن مجاني ومنتجات أصلية",
    "free_gift_subtitle_en": "Regional shipping thresholds, safe checkout, and premium Enfant care for GCC families.",
    "free_gift_subtitle_ar": "حدود شحن إقليمية، دفع آمن، وعناية إنفانت الفاخرة للعائلات في الخليج.",
    "why_choose_links": [
        {
            "label_en": "Why Families Trust Enfant",
            "label_ar": "لماذا تثق العائلات بإنفانت",
            "href": "#story",
        },
        {
            "label_en": "Our Promise – Gentle Care for Delicate Skin",
            "label_ar": "وعدنا – عناية لطيفة للبشرة الحساسة",
            "href": "#promise",
        },
        {
            "label_en": "Our Ingredients – Pure, Safe, and Organic",
            "label_ar": "مكوناتنا – نقية وآمنة وعضوية",
            "href": "#ingredients",
        },
        {
            "label_en": "Dermatologically Tested – Safe for Sensitive Skin",
            "label_ar": "مختبر جلديًا – آمن للبشرة الحساسة",
            "href": "#tested",
        },
    ],
    "policy_links": [
        {"label_en": "Privacy Policy", "label_ar": "سياسة الخصوصية", "href": "#privacy"},
        {"label_en": "Cookie Policy", "label_ar": "سياسة ملفات تعريف الارتباط", "href": "#cookie"},
        {"label_en": "Payment Options", "label_ar": "خيارات الدفع", "href": "#payments"},
        {"label_en": "Terms of Service", "label_ar": "شروط الخدمة", "href": "#terms"},
        {"label_en": "Return & Refund Policy", "label_ar": "سياسة الإرجاع والاسترداد", "href": "#returns"},
        {"label_en": "Shipping Info", "label_ar": "معلومات الشحن", "href": "#shipping"},
    ],
    "static_links": [
        {"label_en": "Contact", "label_ar": "اتصال", "href": "#contact"},
        {"label_en": "About Us", "label_ar": "معلومات عنا", "href": "#about"},
    ],
}

REGIONS = [
    {
        "code": "om",
        "name_en": "Oman",
        "name_ar": "عُمان",
        "currency_code": "OMR",
        "locale_code": "en-OM",
        "shipping_threshold": "20.00",
        "contact_phone": "+968 92412764",
        "contact_email": "info@ayzlin.com",
        "address_en": "Building No.5905, Floor No.3, Flat No.33, Mabella Near Mall of Muscat, Sultanate of Oman",
        "address_ar": "المبنى رقم 5905، الطابق الثالث، الشقة 33، المعبيلة بالقرب من مول مسقط، سلطنة عُمان",
        "is_default": True,
        "sort_order": 1,
    },
    {
        "code": "ae",
        "name_en": "United Arab Emirates",
        "name_ar": "الإمارات العربية المتحدة",
        "currency_code": "AED",
        "locale_code": "en-AE",
        "shipping_threshold": "220.00",
        "contact_phone": "+971 50 121 2269",
        "contact_email": "info@ayzlin.com",
        "address_en": "IFZA Business Park - Building A02 - Dubai Silicon Oasis - Industrial Area - Dubai - United Arab Emirates",
        "address_ar": "مجمع IFZA للأعمال - المبنى A02 - واحة دبي للسيليكون - المنطقة الصناعية - دبي - الإمارات العربية المتحدة",
        "is_default": False,
        "sort_order": 2,
    },
    {
        "code": "sa",
        "name_en": "Saudi Arabia",
        "name_ar": "المملكة العربية السعودية",
        "currency_code": "SAR",
        "locale_code": "en-SA",
        "shipping_threshold": "220.00",
        "contact_phone": "+966 55 100 2211",
        "contact_email": "info@ayzlin.com",
        "address_en": "Riyadh fulfillment support for Saudi Arabia region",
        "address_ar": "دعم الشحن الإقليمي للمملكة العربية السعودية من الرياض",
        "is_default": False,
        "sort_order": 3,
    },
]

HERO_PROMO_CARDS = [
    {
        "title_en": "Extra Mild Moisture Lotion",
        "title_ar": "لوشن الترطيب فائق اللطف",
        "subtitle_en": "A premium daily lotion for delicate baby skin, designed for GCC dryness with a soft, silky finish.",
        "subtitle_ar": "لوشن يومي فاخر لبشرة الطفل الحساسة، مصمم لمواجهة جفاف أجواء الخليج بملمس ناعم وحريري.",
        "cta_en": "Shop daily moisture",
        "cta_ar": "تسوق الترطيب اليومي",
        "href": "/collections",
        "image": ENFANT_ASSETS["extra_mild"],
        "size": "large",
        "accent": "soft",
        "sort_order": 1,
    },
    {
        "title_en": "Double Moisture Lotion",
        "title_ar": "لوشن الترطيب المزدوج",
        "subtitle_en": "Rich nourishment with certified organic ingredients to protect skin comfort through warm days and AC nights.",
        "subtitle_ar": "ترطيب غني بمكونات عضوية معتمدة لحماية راحة البشرة خلال الأيام الحارة وليالي التكييف.",
        "cta_en": "See best seller",
        "cta_ar": "شاهد الأكثر مبيعًا",
        "href": "/collections",
        "image": ENFANT_ASSETS["double_moisture"],
        "size": "small",
        "accent": "moisture",
        "sort_order": 2,
    },
    {
        "title_en": "Relax Moisturizing Lotion",
        "title_ar": "لوشن الترطيب المريح",
        "subtitle_en": "A calmer bedtime routine with comforting moisture for sensitive baby skin.",
        "subtitle_ar": "روتين مسائي أكثر هدوءًا مع ترطيب مريح لبشرة الطفل الحساسة.",
        "cta_en": "Night routine",
        "cta_ar": "روتين المساء",
        "href": "/collections",
        "image": ENFANT_ASSETS["relax"],
        "size": "small",
        "accent": "relax",
        "sort_order": 3,
    },
    {
        "title_en": "Daily Sun Protection",
        "title_ar": "حماية يومية من الشمس",
        "subtitle_en": "Lightweight sun care for everyday family outings, made to feel gentle and breathable.",
        "subtitle_ar": "عناية خفيفة من الشمس للنزهات اليومية، بملمس لطيف ومريح على البشرة.",
        "cta_en": "Explore sun care",
        "cta_ar": "اكتشف العناية الشمسية",
        "href": "/collections",
        "image": ENFANT_ASSETS["daily_sun"],
        "size": "small",
        "accent": "sun",
        "sort_order": 4,
    },
]

CATEGORIES = [
    {"slug": "baby-sets", "name_en": "Gift Sets", "name_ar": "مجموعات الهدايا", "description_en": "Curated Enfant bundles for gifting and first routines.", "description_ar": "حزم إنفانت مختارة للهدايا وروتين البدايات.", "image": ENFANT_ASSETS["extra_mild"], "sort_order": 1},
    {"slug": "baby-oil", "name_en": "Relaxing Care", "name_ar": "عناية مهدئة", "description_en": "Comfort-led night care for calmer bedtime routines.", "description_ar": "عناية مريحة لروتين مسائي أكثر هدوءًا.", "image": ENFANT_ASSETS["relax"], "sort_order": 2},
    {"slug": "baby-lotions", "name_en": "Baby Lotions", "name_ar": "لوشن الأطفال", "description_en": "Moisture-first care for soft daily skin routines.", "description_ar": "عناية يومية قائمة على الترطيب لبشرة ناعمة ومريحة.", "image": ENFANT_ASSETS["double_moisture"], "sort_order": 3},
    {"slug": "cotton-buds", "name_en": "Sensitive Skin Care", "name_ar": "عناية للبشرة الحساسة", "description_en": "Ultra-gentle daily essentials for delicate baby skin.", "description_ar": "أساسيات يومية فائقة اللطف لبشرة الطفل الحساسة.", "image": ENFANT_ASSETS["extra_mild"], "sort_order": 4},
    {"slug": "baby-powder", "name_en": "Daily Moisture", "name_ar": "الترطيب اليومي", "description_en": "Core lotions for everyday comfort and softness.", "description_ar": "لوشنات أساسية للراحة والنعومة اليومية.", "image": ENFANT_ASSETS["double_moisture"], "sort_order": 5},
    {"slug": "nurturing-balm", "name_en": "Complete Care Cream", "name_ar": "كريم العناية المتكاملة", "description_en": "Soothing relief for diaper rash, dry skin, and fragile skin barriers.", "description_ar": "راحة مهدئة لالتهابات الحفاض وجفاف البشرة وضعف الحاجز الجلدي.", "image": ENFANT_ASSETS["complete_care"], "sort_order": 6},
    {"slug": "baby-conditioners", "name_en": "Comfort Care", "name_ar": "عناية مريحة", "description_en": "Soft care picks for delicate scalp and skin comfort.", "description_ar": "خيارات عناية ناعمة لراحة فروة الرأس والبشرة الحساسة.", "image": ENFANT_ASSETS["relax"], "sort_order": 7},
    {"slug": "shampoo-body-wash", "name_en": "Bath & Shampoo", "name_ar": "الاستحمام والشامبو", "description_en": "Wash-day essentials with a gentle moisture balance.", "description_ar": "أساسيات يوم الاستحمام بترطيب لطيف ومتوازن.", "image": ENFANT_ASSETS["moisture_shampoo"], "sort_order": 8},
    {"slug": "baby-mosquito-repellents", "name_en": "Outdoor Protection", "name_ar": "الحماية الخارجية", "description_en": "Gentle outdoor protection with baby-safe comfort.", "description_ar": "حماية خارجية لطيفة مع راحة آمنة للأطفال.", "image": ENFANT_ASSETS["insect_repellent"], "sort_order": 9},
    {"slug": "baby-safe-cleaning", "name_en": "Baby Wipes", "name_ar": "مناديل الأطفال", "description_en": "Face and body wipes made for delicate skin cleanup.", "description_ar": "مناديل للوجه والجسم مناسبة لتنظيف بشرة الطفل الحساسة.", "image": ENFANT_ASSETS["wipes"], "sort_order": 10},
    {"slug": "toothpaste-oral-care", "name_en": "Sun Protection", "name_ar": "الحماية من الشمس", "description_en": "Daily SPF care made for family outings and sensitive skin.", "description_ar": "عناية يومية بعامل حماية مناسبة للنزهات العائلية والبشرة الحساسة.", "image": ENFANT_ASSETS["face_body_sunscreen"], "sort_order": 11},
]

TAGS = [
    {"slug": "organic", "name_en": "Organic", "name_ar": "عضوي", "sort_order": 1},
    {"slug": "new", "name_en": "New Arrival", "name_ar": "وصل حديثًا", "sort_order": 2},
    {"slug": "giftable", "name_en": "Giftable", "name_ar": "مناسب للهدايا", "sort_order": 3},
    {"slug": "sensitive-skin", "name_en": "Sensitive Skin", "name_ar": "بشرة حساسة", "sort_order": 4},
    {"slug": "top-choice", "name_en": "Top Choice", "name_ar": "الأكثر اختيارًا", "sort_order": 5},
]

PRODUCTS = [
    {
        "slug": "sweet-dreams-baby-powder",
        "name_en": "ENFANT Organic Double Moisture Lotion 250 ML",
        "name_ar": "لوشن إنفانت العضوي بالترطيب المزدوج 250 مل",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "Deep daily moisture to nourish and protect delicate baby skin.",
        "short_description_ar": "ترطيب يومي عميق لتغذية وحماية بشرة الطفل الحساسة.",
        "description_en": "A rich moisturizing lotion crafted for delicate baby skin, balancing long-lasting comfort with a soft non-sticky finish.",
        "description_ar": "لوشن مرطب غني مصمم لبشرة الطفل الحساسة، يمنح راحة طويلة الأمد بملمس ناعم غير لزج.",
        "details_en": ["Certified organic chamomile and argan oil", "Comforting moisture for daily use", "Made for delicate and dry baby skin"],
        "details_ar": ["بابونج عضوي معتمد وزيت الأرجان", "ترطيب مريح للاستخدام اليومي", "مناسب لبشرة الطفل الحساسة والجافة"],
        "reviews_en": [{"name": "Noura", "copy": "This is the lotion I reach for most when my baby’s skin needs extra comfort."}],
        "reviews_ar": [{"name": "نورة", "copy": "هذا هو اللوشن الذي أعود إليه دائمًا عندما تحتاج بشرة طفلي إلى راحة إضافية."}],
        "badge_en": "Organic",
        "badge_ar": "عضوي",
        "review_count": 26,
        "rating": "4.8",
        "image": ENFANT_ASSETS["double_moisture"],
        "hover_image": ENFANT_ASSETS["relax"],
        "gallery": [
            ENFANT_ASSETS["double_moisture"],
            ENFANT_ASSETS["relax"],
            ENFANT_ASSETS["extra_mild"],
        ],
        "option_groups_en": [{"name": "Size", "values": ["100 ml"]}],
        "option_groups_ar": [{"name": "الحجم", "values": ["100 مل"]}],
        "show_in_new_arrivals": True,
        "show_in_baby_sets": False,
        "show_in_top_choices": True,
        "is_published": True,
        "category_slug": "baby-lotions",
        "tag_slugs": ["organic", "new"],
        "sort_order": 1,
        "prices": {
            "om": {"price": "4.60", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "44.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "45.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
    {
        "slug": "extra-mild-moisture-lotion",
        "name_en": "ENFANT Organic Plus Extra Mild Moisture Lotion",
        "name_ar": "لوشن إنفانت أورجانيك بلس فائق اللطف",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "Hypoallergenic moisture support for sensitive baby skin.",
        "short_description_ar": "ترطيب مضاد للحساسية للبشرة الحساسة للأطفال.",
        "description_en": "A daily lotion made for GCC dryness with a lightweight finish, easy absorption, and a gentle organic formula.",
        "description_ar": "لوشن يومي مصمم لجفاف أجواء الخليج بملمس خفيف وامتصاص سريع وتركيبة عضوية لطيفة.",
        "details_en": ["Hypoallergenic daily use", "Soft finish with fast absorption", "Suitable for sensitive skin"],
        "details_ar": ["مناسب للاستخدام اليومي المضاد للحساسية", "ملمس ناعم وامتصاص سريع", "مناسب للبشرة الحساسة"],
        "reviews_en": [{"name": "Sara", "copy": "This lotion helped us through dry AC days in Dubai."}],
        "reviews_ar": [{"name": "سارة", "copy": "هذا اللوشن ساعدنا كثيرًا في أيام التكييف الجافة في دبي."}],
        "badge_en": "Organic",
        "badge_ar": "عضوي",
        "review_count": 37,
        "rating": "4.9",
        "image": ENFANT_ASSETS["extra_mild"],
        "hover_image": ENFANT_ASSETS["double_moisture"],
        "gallery": [
            ENFANT_ASSETS["extra_mild"],
            ENFANT_ASSETS["double_moisture"],
            ENFANT_ASSETS["relax"],
        ],
        "option_groups_en": [{"name": "Size", "values": ["250 ml"]}],
        "option_groups_ar": [{"name": "الحجم", "values": ["250 مل"]}],
        "show_in_new_arrivals": True,
        "show_in_baby_sets": False,
        "show_in_top_choices": False,
        "is_published": True,
        "category_slug": "baby-lotions",
        "tag_slugs": ["organic", "sensitive-skin"],
        "sort_order": 2,
        "prices": {
            "om": {"price": "4.40", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "42.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "43.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
    {
        "slug": "natural-mosquito-repellent-spray",
        "name_en": "ENFANT Organic Bye Bye Insect Repellent Lotion",
        "name_ar": "لوشن إنفانت العضوي لطرد الحشرات",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "Gentle outdoor protection with a soft lotion texture for everyday family use.",
        "short_description_ar": "حماية خارجية لطيفة بتركيبة لوشن ناعمة للاستخدام اليومي للعائلة.",
        "description_en": "A baby-friendly repellent lotion that supports evenings outdoors without the harsh feel of strong adult formulas.",
        "description_ar": "لوشن طارد للحشرات مناسب للأطفال يمنح حماية خارجية من دون الإحساس القاسي الموجود في التركيبات القوية للكبار.",
        "details_en": ["Gentle repellent care", "Comfortable lotion finish", "Made for family outings and evening walks"],
        "details_ar": ["عناية لطيفة لطرد الحشرات", "ملمس لوشن مريح", "مناسب للنزهات العائلية والمشاوير المسائية"],
        "reviews_en": [{"name": "Ali", "copy": "A smart outdoor essential that still feels gentle on baby skin."}],
        "reviews_ar": [{"name": "علي", "copy": "منتج أساسي للخروج ويظل لطيفًا على بشرة الطفل."}],
        "badge_en": "Outdoor",
        "badge_ar": "للخارج",
        "review_count": 29,
        "rating": "4.8",
        "image": ENFANT_ASSETS["insect_repellent"],
        "hover_image": ENFANT_ASSETS["extra_mild"],
        "gallery": [
            ENFANT_ASSETS["insect_repellent"],
            ENFANT_ASSETS["extra_mild"],
            ENFANT_ASSETS["face_body_sunscreen"],
        ],
        "option_groups_en": [{"name": "Size", "values": ["100 ml"]}],
        "option_groups_ar": [{"name": "الحجم", "values": ["100 مل"]}],
        "show_in_new_arrivals": True,
        "show_in_baby_sets": False,
        "show_in_top_choices": False,
        "is_published": True,
        "category_slug": "baby-mosquito-repellents",
        "tag_slugs": ["new"],
        "sort_order": 3,
        "prices": {
            "om": {"price": "4.90", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "47.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "48.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
    {
        "slug": "organic-kids-toothpaste",
        "name_en": "ENFANT Face & Body Sunscreen Lotion 70ml",
        "name_ar": "لوشن إنفانت الواقي من الشمس للوجه والجسم 70 مل",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "Compact sun protection designed for stroller walks, beach bags, and everyday family outings.",
        "short_description_ar": "حماية شمسية عملية للمشاوير اليومية وحقيبة الشاطئ والتنقل مع الأطفال.",
        "description_en": "A lightweight face and body sunscreen lotion made for sensitive skin comfort, with a compact format that is easy to carry.",
        "description_ar": "لوشن واقٍ من الشمس للوجه والجسم بملمس خفيف وراحة مناسبة للبشرة الحساسة، مع حجم عملي سهل الحمل.",
        "details_en": ["Compact 70ml format", "Face and body use", "Made for daily sun care on sensitive skin"],
        "details_ar": ["حجم عملي 70 مل", "للوجه والجسم", "مصمم للعناية اليومية من الشمس على البشرة الحساسة"],
        "reviews_en": [{"name": "Maha", "copy": "The size is perfect for my diaper bag and the texture feels light."}],
        "reviews_ar": [{"name": "مها", "copy": "الحجم مثالي لحقيبة الطفل والملمس خفيف جدًا."}],
        "badge_en": "Sun Care",
        "badge_ar": "عناية شمسية",
        "review_count": 33,
        "rating": "4.8",
        "image": ENFANT_ASSETS["face_body_sunscreen"],
        "hover_image": ENFANT_ASSETS["daily_sun"],
        "gallery": [
            ENFANT_ASSETS["face_body_sunscreen"],
            ENFANT_ASSETS["daily_sun"],
            ENFANT_ASSETS["double_moisture"],
        ],
        "option_groups_en": [{"name": "Size", "values": ["70 ml"]}],
        "option_groups_ar": [{"name": "الحجم", "values": ["70 مل"]}],
        "show_in_new_arrivals": True,
        "show_in_baby_sets": False,
        "show_in_top_choices": False,
        "is_published": True,
        "category_slug": "toothpaste-oral-care",
        "tag_slugs": ["organic"],
        "sort_order": 4,
        "prices": {
            "om": {"price": "5.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "48.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "49.00", "compare_at_price": None, "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
    {
        "slug": "extra-mild-baby-wipes",
        "name_en": "ENFANT Organic Plus Extra Mild Baby Wipes",
        "name_ar": "مناديل إنفانت أورجانيك بلس فائقة اللطف للأطفال",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "99% pure water wipes for face and body care.",
        "short_description_ar": "مناديل 99% ماء نقي للوجه والجسم.",
        "description_en": "Fragrance-free plant-based wipes for newborn care, nursery bags, and everyday cleanup.",
        "description_ar": "مناديل نباتية خالية من العطور للعناية بالمواليد وحقائب الأطفال والتنظيف اليومي.",
        "details_en": ["99% pure water", "Plant-based wipe sheet", "Fragrance-free sensitive-skin care"],
        "details_ar": ["99% ماء نقي", "نسيج مناديل نباتي", "عناية خالية من العطور للبشرة الحساسة"],
        "reviews_en": [{"name": "Huda", "copy": "These wipes stay gentle enough for face and body."}],
        "reviews_ar": [{"name": "هدى", "copy": "هذه المناديل لطيفة بما يكفي للوجه والجسم."}],
        "badge_en": "Best Seller",
        "badge_ar": "الأكثر مبيعًا",
        "review_count": 42,
        "rating": "4.9",
        "image": ENFANT_ASSETS["wipes"],
        "hover_image": ENFANT_ASSETS["extra_mild"],
        "gallery": [
            ENFANT_ASSETS["wipes"],
            ENFANT_ASSETS["extra_mild"],
            ENFANT_ASSETS["double_moisture"],
        ],
        "option_groups_en": [{"name": "Pack", "values": ["Single", "3 Pack"]}],
        "option_groups_ar": [{"name": "العبوة", "values": ["قطعة واحدة", "3 عبوات"]}],
        "show_in_new_arrivals": True,
        "show_in_baby_sets": False,
        "show_in_top_choices": False,
        "is_published": True,
        "category_slug": "baby-safe-cleaning",
        "tag_slugs": ["sensitive-skin", "top-choice"],
        "sort_order": 5,
        "prices": {
            "om": {"price": "0.70", "compare_at_price": None, "price_prefix_en": "From", "price_prefix_ar": "ابتداءً من", "unit_price_text_en": "0.040 OMR / mm", "unit_price_text_ar": "0.040 ر.ع / مم"},
            "ae": {"price": "6.50", "compare_at_price": None, "price_prefix_en": "From", "price_prefix_ar": "ابتداءً من", "unit_price_text_en": "0.38 AED / mm", "unit_price_text_ar": "0.38 د.إ / مم"},
            "sa": {"price": "6.70", "compare_at_price": None, "price_prefix_en": "From", "price_prefix_ar": "ابتداءً من", "unit_price_text_en": "0.39 SAR / mm", "unit_price_text_ar": "0.39 ر.س / مم"},
        },
    },
    {
        "slug": "newborn-gift-set-sweet-dream",
        "name_en": "ENFANT Newborn Baby Gift Set - Relaxing Sweet Dream Night Routine",
        "name_ar": "مجموعة هدايا إنفانت لحديثي الولادة - روتين نوم سويت دريم",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "A high-value bedtime bundle for newborn gifting.",
        "short_description_ar": "حزمة ليلية عالية القيمة لهدايا حديثي الولادة.",
        "description_en": "A bundled nighttime routine combining Enfant’s softest organic care products for a calm gift-ready setup.",
        "description_ar": "روتين ليلي متكامل يجمع ألطف منتجات إنفانت العضوية في مجموعة جاهزة للهدايا.",
        "details_en": ["Bundle pricing", "Gift-ready presentation", "Core bedtime essentials"],
        "details_ar": ["سعر مجمع", "تغليف مناسب للهدايا", "أساسيات وقت النوم"],
        "reviews_en": [{"name": "Reem", "copy": "We used this set as a baby shower gift and it felt very premium."}],
        "reviews_ar": [{"name": "ريم", "copy": "استخدمنا هذه المجموعة كهدية استقبال مولود وكانت فاخرة جدًا."}],
        "badge_en": "43% OFF",
        "badge_ar": "خصم 43%",
        "review_count": 46,
        "rating": "4.9",
        "image": ENFANT_ASSETS["extra_mild"],
        "hover_image": ENFANT_ASSETS["double_moisture"],
        "gallery": [
            ENFANT_ASSETS["extra_mild"],
            ENFANT_ASSETS["double_moisture"],
            ENFANT_ASSETS["relax"],
        ],
        "option_groups_en": [{"name": "Set", "values": ["Standard Set"]}],
        "option_groups_ar": [{"name": "المجموعة", "values": ["مجموعة أساسية"]}],
        "show_in_new_arrivals": False,
        "show_in_baby_sets": True,
        "show_in_top_choices": False,
        "is_published": True,
        "category_slug": "baby-sets",
        "tag_slugs": ["giftable", "top-choice"],
        "sort_order": 6,
        "prices": {
            "om": {"price": "23.00", "compare_at_price": "41.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "220.00", "compare_at_price": "390.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "225.00", "compare_at_price": "399.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
    {
        "slug": "ultimate-organic-newborn-essential-kit",
        "name_en": "ENFANT Start in Life - Ultimate Organic Newborn Essential Kit",
        "name_ar": "مجموعة إنفانت ستارت إن لايف - أساسيات عضوية متكاملة لحديثي الولادة",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "A head-to-toe care kit tailored for first-time parents.",
        "short_description_ar": "مجموعة عناية كاملة من الرأس إلى القدمين مصممة للآباء الجدد.",
        "description_en": "This bundle packages the most important Enfant care products into one convenient set for newborn homes.",
        "description_ar": "تجمع هذه الحزمة أهم منتجات إنفانت للعناية في مجموعة واحدة مناسبة لمنازل المواليد الجدد.",
        "details_en": ["Head-to-toe routine", "Great for first-time parents", "Strong bundle value"],
        "details_ar": ["روتين كامل من الرأس إلى القدمين", "مثالية للوالدين الجدد", "قيمة عالية للحزمة"],
        "reviews_en": [{"name": "Haneen", "copy": "A smart first purchase if you want one complete newborn kit."}],
        "reviews_ar": [{"name": "حنين", "copy": "شراء ذكي إذا كنت تريد مجموعة متكاملة لحديثي الولادة."}],
        "badge_en": "43% OFF",
        "badge_ar": "خصم 43%",
        "review_count": 39,
        "rating": "4.8",
        "image": ENFANT_ASSETS["complete_care"],
        "hover_image": ENFANT_ASSETS["relax"],
        "gallery": [
            ENFANT_ASSETS["complete_care"],
            ENFANT_ASSETS["relax"],
            ENFANT_ASSETS["daily_sun"],
        ],
        "option_groups_en": [{"name": "Set", "values": ["Full Kit"]}],
        "option_groups_ar": [{"name": "المجموعة", "values": ["المجموعة الكاملة"]}],
        "show_in_new_arrivals": False,
        "show_in_baby_sets": True,
        "show_in_top_choices": False,
        "is_published": True,
        "category_slug": "baby-sets",
        "tag_slugs": ["giftable"],
        "sort_order": 7,
        "prices": {
            "om": {"price": "23.00", "compare_at_price": "41.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "220.00", "compare_at_price": "390.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "225.00", "compare_at_price": "399.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
    {
        "slug": "sweet-dream-foam-mousse-400ml",
        "name_en": "ENFANT Organic Plus Moisture Shampoo 300ml",
        "name_ar": "شامبو إنفانت أورجانيك بلس المرطب 300 مل",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "A moisture-balanced shampoo that cleans gently while keeping delicate hair and scalp comfortable.",
        "short_description_ar": "شامبو متوازن في الترطيب ينظف بلطف ويحافظ على راحة الشعر وفروة الرأس الحساسة.",
        "description_en": "A gentle shampoo with a soft cleansing feel, created for delicate hair and scalp care in everyday baby routines.",
        "description_ar": "شامبو لطيف بتركيبة تنظيف ناعمة، صُمم للعناية اليومية بالشعر وفروة الرأس الحساسة.",
        "details_en": ["Moisture-supporting wash", "Delicate scalp care", "Easy everyday bath routine"],
        "details_ar": ["غسول داعم للترطيب", "عناية بفروة الرأس الحساسة", "روتين استحمام يومي سهل"],
        "reviews_en": [{"name": "Lina", "copy": "It leaves my baby’s hair soft without stripping moisture."}],
        "reviews_ar": [{"name": "لينا", "copy": "يترك شعر طفلي ناعمًا من دون أن يسحب الترطيب."}],
        "badge_en": "20% OFF",
        "badge_ar": "خصم 20%",
        "review_count": 44,
        "rating": "4.9",
        "image": ENFANT_ASSETS["moisture_shampoo"],
        "hover_image": ENFANT_ASSETS["extra_mild"],
        "gallery": [
            ENFANT_ASSETS["moisture_shampoo"],
            ENFANT_ASSETS["extra_mild"],
            ENFANT_ASSETS["double_moisture"],
        ],
        "option_groups_en": [{"name": "Size", "values": ["300 ml"]}],
        "option_groups_ar": [{"name": "الحجم", "values": ["300 مل"]}],
        "show_in_new_arrivals": False,
        "show_in_baby_sets": False,
        "show_in_top_choices": True,
        "is_published": True,
        "category_slug": "shampoo-body-wash",
        "tag_slugs": ["top-choice", "organic"],
        "sort_order": 8,
        "prices": {
            "om": {"price": "5.96", "compare_at_price": "7.45", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "57.00", "compare_at_price": "71.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "58.00", "compare_at_price": "72.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
    {
        "slug": "shea-butter-nurturing-baby-balm",
        "name_en": "ENFANT Organic Plus Complete Care Cream",
        "name_ar": "كريم إنفانت أورجانيك بلس للعناية المتكاملة",
        "vendor_en": "ENFANT ORGANICS",
        "vendor_ar": "إنفانت أورجانيكس",
        "short_description_en": "A soothing cream for diaper rash, dryness, and delicate skin flare-ups.",
        "short_description_ar": "كريم مهدئ لالتهابات الحفاض والجفاف وتهيج البشرة الحساسة.",
        "description_en": "An all-in-one complete care cream that comforts fragile skin when it needs a richer, more targeted layer of support.",
        "description_ar": "كريم عناية متكاملة يمنح راحة للبشرة الحساسة عندما تحتاج إلى طبقة أغنى وأكثر تركيزًا من الحماية.",
        "details_en": ["Soothing relief for diaper rash", "Comfort for dry and stressed skin", "Targeted support with a richer finish"],
        "details_ar": ["راحة مهدئة لالتهابات الحفاض", "راحة للبشرة الجافة والمجهدة", "دعم مركز بتركيبة أغنى"],
        "reviews_en": [{"name": "Rania", "copy": "We keep this close whenever we need extra soothing care fast."}],
        "reviews_ar": [{"name": "رانيا", "copy": "نحتفظ بهذا الكريم قريبًا منا كلما احتجنا إلى عناية مهدئة سريعة."}],
        "badge_en": "20% OFF",
        "badge_ar": "خصم 20%",
        "review_count": 35,
        "rating": "4.7",
        "image": ENFANT_ASSETS["complete_care"],
        "hover_image": ENFANT_ASSETS["relax"],
        "gallery": [
            ENFANT_ASSETS["complete_care"],
            ENFANT_ASSETS["relax"],
            ENFANT_ASSETS["daily_sun"],
        ],
        "option_groups_en": [{"name": "Size", "values": ["30 ml"]}],
        "option_groups_ar": [{"name": "الحجم", "values": ["30 مل"]}],
        "show_in_new_arrivals": False,
        "show_in_baby_sets": False,
        "show_in_top_choices": True,
        "is_published": True,
        "category_slug": "nurturing-balm",
        "tag_slugs": ["top-choice", "sensitive-skin"],
        "sort_order": 9,
        "prices": {
            "om": {"price": "3.92", "compare_at_price": "4.90", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "ae": {"price": "38.00", "compare_at_price": "47.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
            "sa": {"price": "39.00", "compare_at_price": "48.00", "price_prefix_en": "", "price_prefix_ar": "", "unit_price_text_en": "", "unit_price_text_ar": ""},
        },
    },
]

TESTIMONIALS = [
    {
        "name": "Ayesha",
        "location_en": "Dubai",
        "location_ar": "دبي",
        "quote_en": "The extra mild moisture lotion feels beautifully soft and keeps my baby comfortable through long AC days.",
        "quote_ar": "لوشن الترطيب فائق اللطف ناعم جدًا ويحافظ على راحة طفلي خلال أيام التكييف الطويلة.",
        "rating": 5,
        "sort_order": 1,
    },
    {
        "name": "Fatima",
        "location_en": "UAE",
        "location_ar": "الإمارات",
        "quote_en": "I love how premium the Enfant lotions feel. The packaging is beautiful and the formula is gentle on sensitive skin.",
        "quote_ar": "أحب الإحساس الفاخر في لوشنات إنفانت. العبوة جميلة والتركيبة لطيفة على البشرة الحساسة.",
        "rating": 5,
        "sort_order": 2,
    },
    {
        "name": "Mariam",
        "location_en": "Muscat",
        "location_ar": "مسقط",
        "quote_en": "The relaxing lotion has become part of our bedtime routine. It leaves the skin calm, moisturized, and never sticky.",
        "quote_ar": "أصبح اللوشن المريح جزءًا من روتيننا الليلي. يترك البشرة هادئة ومرطبة ومن دون لزوجة.",
        "rating": 5,
        "sort_order": 3,
    },
]

INSTAGRAM_POSTS = [
    {"image": ENFANT_ASSETS["extra_mild"], "href": "https://www.instagram.com/enfant_middle_east/", "sort_order": 1},
    {"image": ENFANT_ASSETS["double_moisture"], "href": "https://www.instagram.com/enfant_middle_east/", "sort_order": 2},
    {"image": ENFANT_ASSETS["relax"], "href": "https://www.instagram.com/enfant_middle_east/", "sort_order": 3},
    {"image": ENFANT_ASSETS["daily_sun"], "href": "https://www.instagram.com/enfant_middle_east/", "sort_order": 4},
    {"image": ENFANT_ASSETS["face_body_sunscreen"], "href": "https://www.instagram.com/enfant_middle_east/", "sort_order": 5},
    {"image": ENFANT_ASSETS["complete_care"], "href": "https://www.instagram.com/enfant_middle_east/", "sort_order": 6},
]

BLOG_POSTS = [
    {
        "slug": "understanding-detergents-and-infant-eczema",
        "title_en": "Understanding the Impact of Detergents on Infant Eczema",
        "title_ar": "فهم تأثير المنظفات على إكزيما الأطفال الرضع",
        "excerpt_en": "Is your laundry detergent causing your baby's rash? Learn why optical brighteners can be harsh on sensitive skin.",
        "excerpt_ar": "هل يسبب منظف الملابس طفحًا لبشرة طفلك؟ تعرّف على سبب قسوة المبيضات الضوئية على البشرة الحساسة.",
        "image": ENFANT_ASSETS["wipes"],
        "published_at": date(2026, 4, 4),
        "sort_order": 1,
    },
    {
        "slug": "indoor-oasis-blueprint",
        "title_en": "The Indoor Oasis Blueprint: Combatting AC-Skin Syndrome in GCC Homes",
        "title_ar": "خطة الواحة المنزلية: مواجهة جفاف التكييف في منازل الخليج",
        "excerpt_en": "Discover how to preserve your baby’s skin barrier while living with constant air conditioning.",
        "excerpt_ar": "اكتشف كيف تحافظ على حاجز بشرة طفلك مع الاستخدام المستمر للتكييف.",
        "image": ENFANT_ASSETS["double_moisture"],
        "published_at": date(2026, 4, 3),
        "sort_order": 2,
    },
    {
        "slug": "oral-journey-guide",
        "title_en": "The Oral Journey: A Proactive Guide to GCC Baby Dental Care",
        "title_ar": "رحلة العناية بالفم: دليل استباقي لأسنان الأطفال في الخليج",
        "excerpt_en": "Start the brushing habit early with safe toothpaste and better oral-care choices.",
        "excerpt_ar": "ابدأ عادة تنظيف الأسنان مبكرًا باستخدام معجون آمن وخيارات أفضل للعناية بالفم.",
        "image": ENFANT_ASSETS["face_body_sunscreen"],
        "published_at": date(2026, 4, 2),
        "sort_order": 3,
    },
]
