from django.urls import path

from .api_views.payments import (
    OmannetWebhookView,
    PaymentInitiateView,
    PaymentRetryView,
    PaymobWebhookView,
    PaymentStatusView,
    PaytabsWebhookView,
    ThawaniWebhookView,
)
from .api_views.regions import RegionDetectView
from .api_views.whatsapp import WhatsAppWebhookView
from .api_views.storefront import BlogDetailView, BlogListView, CmsPageDetailView
from .views import (
    AbandonedCartCreateView,
    AnalyticsEventCreateView,
    AddressListCreateView,
    BackInStockRequestCreateView,
    AdminAbandonedCartDetailView,
    AdminAbandonedCartListView,
    AdminBackInStockRequestDetailView,
    AdminBackInStockRequestListView,
    AdminAnalyticsView,
    AdminAuditLogListView,
    AdminBlogPostDetailView,
    AdminBlogPostListCreateView,
    AdminCartMilestoneDetailView,
    AdminCartMilestoneListCreateView,
    AdminCmsPageDetailView,
    AdminCmsPageListCreateView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminCouponDetailView,
    AdminCouponListCreateView,
    AdminCustomerListView,
    AdminCustomerDetailView,
    AdminDashboardView,
    AdminDraftOrderCreateView,
    AdminDraftOrderCustomerSearchView,
    AdminDraftOrderDetailView,
    AdminGiftCardDetailView,
    AdminGiftCardListCreateView,
    AdminHeroPromoCardDetailView,
    AdminHeroPromoCardListCreateView,
    AdminInstagramPostDetailView,
    AdminInstagramPostListCreateView,
    AdminMeView,
    AdminModerationSummaryView,
    AdminOrderDetailView,
    AdminOrderRefundView,
    AdminOrderInvoiceDownloadView,
    AdminOrderListView,
    AdminOrderStatusRollbackView,
    AdminOrderShipmentCreateView,
    AdminOrderTrackingRefreshView,
    AdminPaymentDetailView,
    AdminNewsletterSubscriberListView,
    AdminPaymentListView,
    AdminProductStockDetailView,
    AdminProductStockListCreateView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminRegionListCreateView,
    AdminRegionDetailView,
    AdminApplyConversionView,
    AdminReturnRequestDetailView,
    AdminReturnRequestListView,
    AdminReviewDetailView,
    AdminReviewListView,
    AdminShippingRuleDetailView,
    AdminShippingRuleListCreateView,
    AdminSettingsView,
    AdminPaymobRegionConfigView,
    AdminStaffDetailView,
    AdminStaffListCreateView,
    AdminTaxRateDetailView,
    AdminTaxRateListCreateView,
    AdminWarehouseDetailView,
    AdminWarehouseListCreateView,
    CancelOrderView,
    CatalogPageView,
    CheckoutView,
    CouponValidationView,
    GiftCardValidationView,
    CustomerOrderListView,
    CustomerReturnRequestCreateView,
    CustomerReturnRequestListView,
    GuestOrderLookupView,
    HomePageView,
    NavigationView,
    NewsletterSubscriptionView,
    OrderDetailView,
    OrderInvoiceDownloadView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    ProductDetailView,
    ProductListView,
    PushDeviceDeactivateView,
    PushDeviceRegisterView,
    RegisterView,
    ReportCsvView,
    ReviewCreateView,
    SearchSuggestionsView,
    WishlistView,
)


urlpatterns = [
    path("navigation/", NavigationView.as_view(), name="navigation"),
    path("regions/detect/", RegionDetectView.as_view(), name="regions-detect"),
    path("home/", HomePageView.as_view(), name="home"),
    path("catalog/", CatalogPageView.as_view(), name="catalog"),
    path("products/", ProductListView.as_view(), name="products"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("search/suggestions/", SearchSuggestionsView.as_view(), name="search-suggestions"),
    path("blog/", BlogListView.as_view(), name="blog-list"),
    path("blog/<slug:slug>/", BlogDetailView.as_view(), name="blog-detail"),
    path("pages/<slug:slug>/", CmsPageDetailView.as_view(), name="cms-page-detail"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("payments/initiate/", PaymentInitiateView.as_view(), name="payment-initiate"),
    path("payments/retry/", PaymentRetryView.as_view(), name="payment-retry"),
    path("payments/webhook/", PaymobWebhookView.as_view(), name="payment-webhook"),
    path("payments/webhook/paytabs/", PaytabsWebhookView.as_view(), name="payment-webhook-paytabs"),
    path("payments/webhook/thawani/", ThawaniWebhookView.as_view(), name="payment-webhook-thawani"),
    path("payments/webhook/omannet/", OmannetWebhookView.as_view(), name="payment-webhook-omannet"),
    path("payments/status/<str:order_number>/", PaymentStatusView.as_view(), name="payment-status"),
    path("coupons/validate/", CouponValidationView.as_view(), name="coupon-validate"),
    path("gift-cards/validate/", GiftCardValidationView.as_view(), name="gift-card-validate"),
    path("orders/lookup/", GuestOrderLookupView.as_view(), name="guest-order-lookup"),
    path("orders/<str:order_number>/", OrderDetailView.as_view(), name="order-detail"),
    path("orders/<str:order_number>/invoice/", OrderInvoiceDownloadView.as_view(), name="order-invoice-download"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/password-reset/", PasswordResetRequestView.as_view(), name="password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("account/profile/", ProfileView.as_view(), name="account-profile"),
    path("account/addresses/", AddressListCreateView.as_view(), name="account-addresses"),
    path("account/orders/", CustomerOrderListView.as_view(), name="account-orders"),
    path("account/orders/<str:order_number>/cancel/", CancelOrderView.as_view(), name="account-order-cancel"),
    path("account/orders/<str:order_number>/returns/", CustomerReturnRequestCreateView.as_view(), name="account-order-return-create"),
    path("account/returns/", CustomerReturnRequestListView.as_view(), name="account-returns"),
    path("account/wishlist/", WishlistView.as_view(), name="account-wishlist"),
    path("reviews/", ReviewCreateView.as_view(), name="review-create"),
    path("newsletter/", NewsletterSubscriptionView.as_view(), name="newsletter"),
    path("stock-notify/", BackInStockRequestCreateView.as_view(), name="stock-notify"),
    path("notifications/devices/", PushDeviceRegisterView.as_view(), name="push-device-register"),
    path("notifications/devices/deactivate/", PushDeviceDeactivateView.as_view(), name="push-device-deactivate"),
    path("notifications/webhook/whatsapp/", WhatsAppWebhookView.as_view(), name="whatsapp-webhook"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/analytics/", AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("admin/me/", AdminMeView.as_view(), name="admin-me"),
    path("admin/audit-logs/", AdminAuditLogListView.as_view(), name="admin-audit-logs"),
    path("admin/moderation/", AdminModerationSummaryView.as_view(), name="admin-moderation"),
    path("admin/newsletter-subscribers/", AdminNewsletterSubscriberListView.as_view(), name="admin-newsletter-subscribers"),
    path("admin/reports/<str:report_type>/", ReportCsvView.as_view(), name="admin-report"),
    path("admin/products/", AdminProductListCreateView.as_view(), name="admin-products"),
    path("admin/products/<slug:slug>/", AdminProductDetailView.as_view(), name="admin-product-detail"),
    path("admin/categories/", AdminCategoryListCreateView.as_view(), name="admin-categories"),
    path("admin/categories/<slug:slug>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("admin/orders/", AdminOrderListView.as_view(), name="admin-orders"),
    path("admin/orders/drafts/", AdminDraftOrderCreateView.as_view(), name="admin-draft-orders-create"),
    path(
        "admin/orders/drafts/customer-search/",
        AdminDraftOrderCustomerSearchView.as_view(),
        name="admin-draft-orders-customer-search",
    ),
    path(
        "admin/orders/drafts/<str:order_number>/",
        AdminDraftOrderDetailView.as_view(),
        name="admin-draft-order-detail",
    ),
    path("admin/orders/<str:order_number>/", AdminOrderDetailView.as_view(), name="admin-order-detail"),
    path(
        "admin/orders/<str:order_number>/status-rollback/",
        AdminOrderStatusRollbackView.as_view(),
        name="admin-order-status-rollback",
    ),
    path("admin/orders/<str:order_number>/refund/", AdminOrderRefundView.as_view(), name="admin-order-refund"),
    path(
        "admin/orders/<str:order_number>/shipment/create/",
        AdminOrderShipmentCreateView.as_view(),
        name="admin-order-shipment-create",
    ),
    path(
        "admin/orders/<str:order_number>/shipment/refresh/",
        AdminOrderTrackingRefreshView.as_view(),
        name="admin-order-shipment-refresh",
    ),
    path(
        "admin/orders/<str:order_number>/invoice/",
        AdminOrderInvoiceDownloadView.as_view(),
        name="admin-order-invoice-download",
    ),
    path("admin/customers/", AdminCustomerListView.as_view(), name="admin-customers"),
    path("admin/customers/<int:pk>/", AdminCustomerDetailView.as_view(), name="admin-customer-detail"),
    path("admin/payments/", AdminPaymentListView.as_view(), name="admin-payments"),
    path("admin/payments/<int:pk>/", AdminPaymentDetailView.as_view(), name="admin-payment-detail"),
    path("admin/promotions/", AdminCouponListCreateView.as_view(), name="admin-promotions"),
    path("admin/promotions/<int:pk>/", AdminCouponDetailView.as_view(), name="admin-promotion-detail"),
    path("admin/reviews/", AdminReviewListView.as_view(), name="admin-reviews"),
    path("admin/reviews/<int:pk>/", AdminReviewDetailView.as_view(), name="admin-review-detail"),
    path("admin/returns/", AdminReturnRequestListView.as_view(), name="admin-returns"),
    path("admin/returns/<int:pk>/", AdminReturnRequestDetailView.as_view(), name="admin-return-detail"),
    path("admin/shipping-rules/", AdminShippingRuleListCreateView.as_view(), name="admin-shipping-rules"),
    path("admin/shipping-rules/<int:pk>/", AdminShippingRuleDetailView.as_view(), name="admin-shipping-rule-detail"),
    path("admin/cart-milestones/", AdminCartMilestoneListCreateView.as_view(), name="admin-cart-milestones"),
    path("admin/cart-milestones/<int:pk>/", AdminCartMilestoneDetailView.as_view(), name="admin-cart-milestone-detail"),
    path("admin/warehouses/", AdminWarehouseListCreateView.as_view(), name="admin-warehouses"),
    path("admin/warehouses/<int:pk>/", AdminWarehouseDetailView.as_view(), name="admin-warehouse-detail"),
    path("admin/product-stocks/", AdminProductStockListCreateView.as_view(), name="admin-product-stocks"),
    path("admin/product-stocks/<int:pk>/", AdminProductStockDetailView.as_view(), name="admin-product-stock-detail"),
    path("admin/blog-posts/", AdminBlogPostListCreateView.as_view(), name="admin-blog-posts"),
    path("admin/blog-posts/<slug:slug>/", AdminBlogPostDetailView.as_view(), name="admin-blog-post-detail"),
    path("admin/cms-pages/", AdminCmsPageListCreateView.as_view(), name="admin-cms-pages"),
    path("admin/cms-pages/<int:pk>/", AdminCmsPageDetailView.as_view(), name="admin-cms-page-detail"),
    path("admin/hero-promo-cards/", AdminHeroPromoCardListCreateView.as_view(), name="admin-hero-promo-cards"),
    path("admin/hero-promo-cards/<int:pk>/", AdminHeroPromoCardDetailView.as_view(), name="admin-hero-promo-card-detail"),
    path("admin/instagram-posts/", AdminInstagramPostListCreateView.as_view(), name="admin-instagram-posts"),
    path("admin/instagram-posts/<int:pk>/", AdminInstagramPostDetailView.as_view(), name="admin-instagram-post-detail"),
    path("admin/regions/", AdminRegionListCreateView.as_view(), name="admin-regions"),
    path("admin/pricing/apply-conversion/", AdminApplyConversionView.as_view(), name="admin-apply-conversion"),
    path("admin/regions/<str:code>/", AdminRegionDetailView.as_view(), name="admin-region-detail"),
    path("admin/tax-rates/", AdminTaxRateListCreateView.as_view(), name="admin-tax-rates"),
    path("admin/tax-rates/<int:pk>/", AdminTaxRateDetailView.as_view(), name="admin-tax-rate-detail"),
    path("admin/staff/", AdminStaffListCreateView.as_view(), name="admin-staff"),
    path("admin/staff/<int:pk>/", AdminStaffDetailView.as_view(), name="admin-staff-detail"),
    path("admin/settings/", AdminSettingsView.as_view(), name="admin-settings"),
    path("admin/paymob-regions/", AdminPaymobRegionConfigView.as_view(), name="admin-paymob-regions"),
    path("admin/gift-cards/", AdminGiftCardListCreateView.as_view(), name="admin-gift-cards"),
    path("admin/gift-cards/<int:pk>/", AdminGiftCardDetailView.as_view(), name="admin-gift-card-detail"),
    path(
        "admin/back-in-stock-requests/",
        AdminBackInStockRequestListView.as_view(),
        name="admin-back-in-stock-requests",
    ),
    path(
        "admin/back-in-stock-requests/<int:pk>/",
        AdminBackInStockRequestDetailView.as_view(),
        name="admin-back-in-stock-request-detail",
    ),
    path("admin/abandoned-carts/", AdminAbandonedCartListView.as_view(), name="admin-abandoned-carts"),
    path("admin/abandoned-carts/<int:pk>/", AdminAbandonedCartDetailView.as_view(), name="admin-abandoned-cart-detail"),
    path("abandoned-carts/", AbandonedCartCreateView.as_view(), name="abandoned-cart-create"),
    path("analytics/event/", AnalyticsEventCreateView.as_view(), name="analytics-event-create"),
]
