from django.urls import path

from .views import (
    AddressListCreateView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminCouponDetailView,
    AdminCouponListCreateView,
    AdminCustomerListView,
    AdminCustomerDetailView,
    AdminDashboardView,
    AdminModerationSummaryView,
    AdminOrderDetailView,
    AdminOrderListView,
    AdminPaymentDetailView,
    AdminPaymentListView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminRegionListView,
    AdminReviewDetailView,
    AdminReviewListView,
    AdminSettingsView,
    CancelOrderView,
    CatalogPageView,
    CheckoutView,
    CouponValidationView,
    CustomerOrderListView,
    GuestOrderLookupView,
    HomePageView,
    NavigationView,
    NewsletterSubscriptionView,
    OrderDetailView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    ProductDetailView,
    ProductListView,
    PushDeviceDeactivateView,
    PushDeviceRegisterView,
    RegisterView,
    ReportCsvView,
    ReviewCreateView,
    WishlistView,
)


urlpatterns = [
    path("navigation/", NavigationView.as_view(), name="navigation"),
    path("home/", HomePageView.as_view(), name="home"),
    path("catalog/", CatalogPageView.as_view(), name="catalog"),
    path("products/", ProductListView.as_view(), name="products"),
    path("products/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("coupons/validate/", CouponValidationView.as_view(), name="coupon-validate"),
    path("orders/lookup/", GuestOrderLookupView.as_view(), name="guest-order-lookup"),
    path("orders/<str:order_number>/", OrderDetailView.as_view(), name="order-detail"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/password-reset/", PasswordResetRequestView.as_view(), name="password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("account/profile/", ProfileView.as_view(), name="account-profile"),
    path("account/addresses/", AddressListCreateView.as_view(), name="account-addresses"),
    path("account/orders/", CustomerOrderListView.as_view(), name="account-orders"),
    path("account/orders/<str:order_number>/cancel/", CancelOrderView.as_view(), name="account-order-cancel"),
    path("account/wishlist/", WishlistView.as_view(), name="account-wishlist"),
    path("reviews/", ReviewCreateView.as_view(), name="review-create"),
    path("newsletter/", NewsletterSubscriptionView.as_view(), name="newsletter"),
    path("notifications/devices/", PushDeviceRegisterView.as_view(), name="push-device-register"),
    path("notifications/devices/deactivate/", PushDeviceDeactivateView.as_view(), name="push-device-deactivate"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/moderation/", AdminModerationSummaryView.as_view(), name="admin-moderation"),
    path("admin/reports/<str:report_type>/", ReportCsvView.as_view(), name="admin-report"),
    path("admin/products/", AdminProductListCreateView.as_view(), name="admin-products"),
    path("admin/products/<slug:slug>/", AdminProductDetailView.as_view(), name="admin-product-detail"),
    path("admin/categories/", AdminCategoryListCreateView.as_view(), name="admin-categories"),
    path("admin/categories/<slug:slug>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("admin/orders/", AdminOrderListView.as_view(), name="admin-orders"),
    path("admin/orders/<str:order_number>/", AdminOrderDetailView.as_view(), name="admin-order-detail"),
    path("admin/customers/", AdminCustomerListView.as_view(), name="admin-customers"),
    path("admin/customers/<int:pk>/", AdminCustomerDetailView.as_view(), name="admin-customer-detail"),
    path("admin/payments/", AdminPaymentListView.as_view(), name="admin-payments"),
    path("admin/payments/<int:pk>/", AdminPaymentDetailView.as_view(), name="admin-payment-detail"),
    path("admin/promotions/", AdminCouponListCreateView.as_view(), name="admin-promotions"),
    path("admin/promotions/<int:pk>/", AdminCouponDetailView.as_view(), name="admin-promotion-detail"),
    path("admin/reviews/", AdminReviewListView.as_view(), name="admin-reviews"),
    path("admin/reviews/<int:pk>/", AdminReviewDetailView.as_view(), name="admin-review-detail"),
    path("admin/regions/", AdminRegionListView.as_view(), name="admin-regions"),
    path("admin/settings/", AdminSettingsView.as_view(), name="admin-settings"),
]
